[versions]
plugin-android = "8.0.1"
plugin-kotlin = "1.7.20"
plugin-ksp = "1.7.20-1.0.8"

jecnaAPI = "3.1.0"

compose-compiler = "1.3.2"
compose-material = "1.4.0-beta02"
compose-material3 = "1.1.0-alpha07"
compose-material-icons-extended = "1.3.1"
compose-destinations = "1.8.33-beta"
compose-state-events = "1.2.3"
compose-html = "1.0.2"
compose-coil = "2.2.2"
activity = "1.6.1"
accompanist = "0.28.0"
hilt = "2.44"
hilt-navigation-compose = "1.0.0"
datastore = "1.0.0"
serialization = "1.5.0"

[libraries]
jecnaAPI = { module = "me.tomasan7:jecna-api", version.ref = "jecnaAPI" }

compose-material = { module = "androidx.compose.material:material", version.ref = "compose-material" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-material-icons-extended" }
compose-destinations-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "compose-destinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destinations" }
compose-state-events = { module = "com.github.leonard-palm:compose-state-events", version.ref = "compose-state-events" }
compose-html = { module = "com.github.ireward:compose-html", version.ref = "compose-html" }
compose-coil = { module = "io.coil-kt:coil-compose", version.ref = "compose-coil" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

[plugins]
android-application = { id = "com.android.application", version.ref = "plugin-android" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "plugin-kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "plugin-ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "plugin-kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "plugin-kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }