[versions]
plugin-android = "7.2.2"
plugin-kotlin = "1.7.10"
plugin-ksp = "1.7.10-1.0.6"

jecnaAPI = "1.2.11"

compose = "1.2.1"
compose-compiler = "1.3.1"
compose-material3 = "1.0.0-beta02"
activity = "1.6.0"
composeDestinations = "1.6.20-beta"
composeHtml = "1.0.2"
accompanist = "0.25.1"
hilt = "2.43.2"
hilt-navigation-compose = "1.0.0"
datastore = "1.0.0"
serialization = "1.4.0"

[libraries]
jecnaAPI = { module = "me.tomasan7:jecna-api", version.ref = "jecnaAPI" }

compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

composeHtml = { module = "com.github.ireward:compose-html", version.ref = "composeHtml" }

composeDestinations-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "composeDestinations" }
composeDestinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "composeDestinations" }

accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

[plugins]
android-application = { id = "com.android.application", version.ref = "plugin-android" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "plugin-kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "plugin-ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "plugin-kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "plugin-kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }